/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capman;

import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import pcap.spi.Address;
import pcap.spi.Interface;

/**
 *
 * @author Hassen
 */
public class DeviceDetails extends javax.swing.JFrame {
    
     Interface device;
   
    /**
     * Creates new form DeviceDetails
     */
   
    public DeviceDetails(Interface device) {
        
        this.device = device;  
        initComponents();
        populateLable(device);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dName = new javax.swing.JLabel();
        dDesc = new javax.swing.JLabel();
        dFlags = new javax.swing.JLabel();
        dAddress = new javax.swing.JLabel();
        dNetmask = new javax.swing.JLabel();
        dBroadcast = new javax.swing.JLabel();
        dDestination = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setText("Description:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText("Flags:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setText("Netmask:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setText("Broadcast:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setText("Destination:");

        dName.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dName.setText("Name:");

        dDesc.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dDesc.setText("Description:");

        dFlags.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dFlags.setText("Flags:");

        dAddress.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dAddress.setText("Address:");

        dNetmask.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dNetmask.setText("Netmask:");

        dBroadcast.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dBroadcast.setText("Broadcast:");

        dDestination.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dDestination.setText("Destination:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dName)
                    .addComponent(dDesc)
                    .addComponent(dFlags)
                    .addComponent(dAddress)
                    .addComponent(dNetmask)
                    .addComponent(dBroadcast)
                    .addComponent(dDestination))
                .addContainerGap(568, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dFlags)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dNetmask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dBroadcast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dDestination))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
       com.formdev.flatlaf.FlatLightLaf.install();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeviceDetails(null).setVisible(true);
            }
        });
    }
    public void populateLable(Interface device){
        dName.setText(device.name());
        dDesc.setText(device.description());
        dFlags.setText(String.valueOf(device.flags()));
        Iterator<Address> addresses = device.addresses().iterator();
        while (addresses.hasNext()) {
            Address address = addresses.next();
            dAddress.setText(String.valueOf( address.address()));
            dNetmask.setText(String.valueOf(address.netmask()));
            dBroadcast.setText(String.valueOf( address.broadcast()));
            dDestination.setText(String.valueOf(address.destination()));
        }      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dAddress;
    private javax.swing.JLabel dBroadcast;
    private javax.swing.JLabel dDesc;
    private javax.swing.JLabel dDestination;
    private javax.swing.JLabel dFlags;
    private javax.swing.JLabel dName;
    private javax.swing.JLabel dNetmask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
