/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capman;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Hassen
 */
public class LaunchFrame extends javax.swing.JFrame {

    /**
     * Creates new form LaunchFrame
     */
    public LaunchFrame() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(LightOption);
        group.add(DarkOption);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        ThemeOptions = new javax.swing.JMenu();
        LightOption = new javax.swing.JCheckBoxMenuItem();
        DarkOption = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        btnStart.setBackground(new java.awt.Color(248, 207, 159));
        btnStart.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(0, 0, 0));
        btnStart.setText("Start");

        File.setText("File");

        Exit.setText("Exit");
        File.add(Exit);

        MenuBar.add(File);

        ThemeOptions.setText("Theme Options");

        LightOption.setSelected(true);
        LightOption.setText("Light Mode");
        LightOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LightOptionItemStateChanged(evt);
            }
        });
        ThemeOptions.add(LightOption);

        DarkOption.setText("Dark Mode");
        DarkOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DarkOptionItemStateChanged(evt);
            }
        });
        ThemeOptions.add(DarkOption);

        MenuBar.add(ThemeOptions);

        jMenu1.setText("About");
        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(410, 410, 410))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblLogo)
                .addGap(53, 53, 53)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LightOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LightOptionItemStateChanged
        setTheme(evt,"light");
    }//GEN-LAST:event_LightOptionItemStateChanged

    private void DarkOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DarkOptionItemStateChanged
        setTheme(evt,"dark");
    }//GEN-LAST:event_DarkOptionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public void setTheme(java.awt.event.ItemEvent evt, String name){
        if (evt.getStateChange() == 1) {
      if ("light".equals(name)) {
        com.formdev.flatlaf.FlatLightLaf.install();
      } else {
        com.formdev.flatlaf.FlatDarculaLaf.install();
      }
      for (java.awt.Window window : javax.swing.JFrame.getWindows()) {
        javax.swing.SwingUtilities.updateComponentTreeUI(window);
      }
    }
     
        
    
    }
    
    public static void main(String args[]) {

        com.formdev.flatlaf.FlatLightLaf.install();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LaunchFrame().setVisible(true);
               
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem DarkOption;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JCheckBoxMenuItem LightOption;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu ThemeOptions;
    private javax.swing.JButton btnStart;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
