/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capman;

import java.awt.Color;

/**
 *
 * @author Hassen
 */
public class SplashFrame extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashFrame() {
         
        this.setUndecorated(true);
        initComponents();
        lblLogo.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        pBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo-500.png"))); // NOI18N
        lblLogo.setOpaque(true);

        pBar.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       int delay = 2000;

    SplashFrame splashFrame = new SplashFrame();
    splashFrame.setVisible(true);
    splashFrame.startProgress(delay);

    try {
      Thread.sleep(delay);
    } catch (InterruptedException e) {
    }

    /* Set default theme */
   com.formdev.flatlaf.FlatLightLaf.install();

    java.awt.EventQueue.invokeLater(() -> {
      new LaunchFrame().setVisible(true);
    });

    splashFrame.dispose();
  }

  void startProgress(int duration) {
    int i = 0;
    try {
      while (i <= 100) {
        pBar.setValue(i);
        Thread.sleep(duration / 10);
        i += 10;
      }
    } catch (InterruptedException e) {
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JProgressBar pBar;
    // End of variables declaration//GEN-END:variables
}
